Add work "Section" in index.html
jellywiz/Project-setup-and-mobile-first pull request #6
Opened 2022-09-23 15:09 UTC by jellywiz

- Create "Work" section inside index.html file
- Create "About me" section inside index.html file
- Add Grid in styles.css file
- Add images for about me and work section

2022-09-23 16:26 UTC, jellywiz commented
- Add main.js
- fix css layout

2022-09-23 17:50 UTC, BertrandConxy requested changes
Hi @jellywiz , 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 


## Highlights 💪 
Great UI 💯 
- No linter errors
- correct flow is used
- good PR


## Required Changes ♻️

- [ ] Great job so far. your work looks great. I looked up your README and I found out that there are some important sections that you need to improve in order for it to look professional 😎. The first one is the `Getting started` section. this is where you describe procedures to clone and run your project locally. It looks great when you add some important commands too 💡 
so please improve it 😃. The second one is to add a `screenshot` of your portfolio so that you give the visitors a quick preview of your website 😉 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 17:50 UTC, BertrandConxy commented on index.html
> +    </script>
- [ ] It is not the best practice to put javascript codes in the HTML file. As a best practice, all the javascript codes should be put in their own file and then referenced on the HTML page. I have seen that you did a great job by implementing a lot of functionalities to finish up the portfolio. I was really amazed 👏 👏 You have done a great job and keep it up. That is why I believe that you are going to correct these few changes as they are essential too 😉

2022-09-23 17:50 UTC, BertrandConxy commented on index.html
> +        <div id="projects-container" class="programmingcontainer">
- [ ] Please use the `section` tag instead of the generic `div` tag because it is more semantic and conveys extra information to the browser about how to present the content and this is great for search engines to rank up your site. 😉 👍

2022-09-23 17:50 UTC, BertrandConxy commented on index.html
> +                        <div class="storysection-column2">
- [ ] It is important to note that at this point, you are not supposed to render the projects section dynamically as this will come after. What you are expected to do in this milestone is to implement them in the HTML as they are on the Figma design. Some of the important points I would suggest is to remember to use the `grid layout` on the projects-container and then you can use `flex layout` in each project card 😉 But you have done great job so far 👏

2022-09-23 17:50 UTC, BertrandConxy commented on index.html
> +        <div id="aboutmeProject" class="aboutmesection">
- [ ] Please use the `section` tag here on this container instead of the generic `div` tag. It is more semantic and considered as best practice to use them 😎

2022-09-23 17:50 UTC, BertrandConxy commented on index.html
> +                    <li class="subline">Gitlab</li>
- [ ] Great job on achieving this layout. It also looks great compared to the Figma design. However, from the markup guidelines that you have to follow, this part is supposed to be implemented as the `nested lists`. It can be somehow tricky to understand, that is why I am going to share with you some tutorial articles that will help you get an idea of what to be done 👉 [HERE](https://www.webucator.com/article/how-to-properly-nest-lists-in-html/) 
REMEMBER: keep your styles looking very well as they are now 😉

2022-09-23 19:19 UTC, jellywiz commented on index.html
> +                        <div class="storysection-column2">
Hi there thanks for the feedback @BertrandConxy do i need to change back to static? or dynamic is fine?

2022-09-23 19:40 UTC, jellywiz commented on index.html
> +                        <div class="storysection-column2">
![image](https://user-images.githubusercontent.com/83097009/192044683-517cb1b5-df8a-4cde-ab66-623a72514b66.png)
![image](https://user-images.githubusercontent.com/83097009/192044777-3a57fda2-40c3-467f-9838-2beb7d0d0762.png)
 i have used grid and flex layout as it was required

2022-09-23 19:46 UTC, jellywiz commented on index.html
> +                    <li class="subline">Gitlab</li>
@BertrandConxy sorry for as the requirements that we have I don't see anything regarding nested list 
![image](https://user-images.githubusercontent.com/83097009/192045688-b5e3022a-6d22-4ead-aaf1-51b8db3513dd.png)

2022-09-23 19:47 UTC, jellywiz commented on index.html
> +                    <li class="subline">Gitlab</li>
@BertrandConxy sorry for as the requirements that we have I don't see anything regarding nested list
![image](https://user-images.githubusercontent.com/83097009/192045814-ccc0528b-0885-42c5-a8c5-ae93f8b4e49f.png)

2022-09-23 23:37 UTC, ichala requested changes
Hi @jellywiz  , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Great Design✅ 
- Linters are passing ✅


 ## Required Changes ♻️

- [ ] 🛑🛑 great job implementing the changes 👏  but as mentioned by the previous reviewer kindly update your ReadMe file to make it look professional 🛑🛑
👇 👇 👇 👇 👇 👇 👇 👇 👇 👇 
![image](https://user-images.githubusercontent.com/89282221/192069636-ed58d1c2-0b1c-4089-98ac-8097e675bb46.png)



## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 00:06 UTC, Olamarx approved these changes
Hi @jellywiz, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/kHy3oajUgi4Ga0rAEY/giphy.gif"/>
[OPTIONAL] You don't need to add the image to the readme file 😄

## Highlights
- Professional Readme file ✔️ 
- Meaningful commit messages 👍🏼 
- Good use of Git and Github flow ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 00:06 UTC, merged